paths:
  install: 'D:\Servers\Empyrion\'
  osfmount: 'D:\Servers\Tools\OSFMount\osfmount.com'
  peazip: 'D:\Servers\Tools\PeaZip\res\bin\7z\7z.exe'
  empremoteclient: 'D:\Servers\Tools\esm\emprc\EmpyrionPrime.RemoteClient.Console.exe'
  eah: 'D:\Servers\Empyrion\DedicatedServer\EmpyrionAdminHelper'
  steamcmd: 'D:\Servers\Tools\steamcmd\steamcmd.exe'

server:
  dedicatedYaml: "esm-dedicated.yaml"
  gfxMode: True
  minDiskSpaceForStartup: 500M

ramdisk:
  size: "1G"
  synchronizeRamToMirrorInterval: 360

communication:
  announceSyncProbability: 0.1

  haimsterEnabled: True                  # enables haimster integration, which requires a running haimster server
  haimsterHost: http://192.168.1.102:8000     # the url to the haimster server
  playerNameCacheTime: 300                # time in seconds to cache player names for, since they need to be retrieved from the database
  incomingMessageHostIp: 0.0.0.0          # the host url to bind our http server to to receive messages from haimster. This ip and port must be configured on haimster side aswell.
  incomingMessageHostPort: 9000           # the port to bind to to receive messages from haimster. This ip and port must be configured on haimster side aswell.
  
backups:
  additionalBackupPaths: # list of full paths to source files or directories to backup additionally. Those will all end up in the folder "Additional" in the backup.
    - 'D:/Servers/Empyrion/Content/Mods/EncryptoidModPack' # the whole modpack
    - 'D:/Servers/Tools/esm/esm-custom-config.yaml' # our own configuration

updates: 
  scenariosource: 'D:/Servers/Scenarios/ProjectA' # source directory with the scenario files that will be copied to the servers scenario folder.
  additional: # additional stuff to copy when calling the esm game-update command
    # If a path is relative, it will be assumed to be relative to the installation path.
    # source path globs (wildcards) are supported
    # if dst does not exist and is not a directory, a directory with that name will be created and used as target for the source.
    # if src is a directory, it will be copied recursively into the target folder.
    # existing files/directories in the target will be overwritten!
    #
    # copy all item icons from the scenario to EAH
    - {src: 'D:/Servers/Scenarios/ProjectA/SharedData/Content/Bundles/ItemIcons/*.*', dst: 'D:/Servers/Empyrion/DedicatedServer/EmpyrionAdminHelper/Items/'}
    # copy custom sqlqueries to the game config
    - {src: 'D:/Servers/Misc/server_rankings/SqlQueries_disabled.txt', dst: 'D:/Servers/Empyrion/Content/Configuration/SqlQueries.txt'}

deletes:
  additionalDeletes: # additional paths of stuff to delete when using the "deleteall" command
    # paths to files/directories could point to like mod data, etc.. This accepts filesystem globbing (wildcards) like *.dat or similar.
    # if a path is relative, it will be assumed to be relative to the installation path.
    - 'Content/Mods/EncryptoidModPack/Mods/AdminTetherport/Database'
    
galaxy:
  territories: # custom faction territory definitions, esm will read out the galaxy config dynamically
     - faction: "MyCustomTerritory"
       center-x: 155
       center-y: 10
       center-z: -360
       radius: 35
     - faction: "RandomRegionILikeWiping"
       center-x: 12
       center-y: 34
       center-z: -56
       radius: 78
