name: release workflow

# triggers the workflow on any push to a tag (including when a tag is created)
on:
  push:
    tags:
      - "*"

jobs:
  release-esm-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Update project version
        run: |
          # set the version in the pyproject.toml to the git tag
          (Get-Content pyproject.toml) -replace 'version\s*=\s*"(.*)"', "version = `"${{ github.ref_name }}`"" | Set-Content pyproject.toml
  
      - name: Run PyInstaller
        run: |
          python -m PyInstaller esm.spec --noconfirm

      - name: Info before release
        run: |
          echo "github.ref_name is: ${{ github.ref_name }}"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.ref_name }} dist/esm-${{ github.ref_name }}.zip

      - name: Commit version changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"          
          git add pyproject.toml
          git commit -m "Automatically update version number for next development iteration"
          git push origin main
